### ISSUE TITLE
KMO score

### ISSUE THREAD

**Issue by Balasubra** [RUBi-ZA/MODE-TASK#25]
Dear team-members,
My congratulations for this wonderful tool. I see that the **get_kmo** function is taking covariance matrix as the input. Is it nt supposed to take the correlation matrix as the input ?.

I quickly looked into the book "Comparitive approach to using R and python for statistical data analysis" (page 174) referred inside your code from which i get that the input for the KMO is actually a correlation matrix and not the covariance matrix. Just for curiosity, i cross-checked the implementation of KMO score in another library (https://factor-analyzer.readthedocs.io/en/latest/_modules/factor_analyzer/factor_analyzer.html) and i find that they use the correlation matrix indeed. 

Am i missing something ?

Thanks,
Bala

**Comment by nizamibilal** [comment]
Hi, Sorry for such a long silence, and thanks for reporting it. I have fixed the issue. Please give it a try.

**Comment by nizamibilal** [comment]
I'm closing this issue. Reopen if necessary.
