### ISSUE TITLE
Post analysis from PCA and tSNE

### ISSUE THREAD

**Issue by sbhakat** [RUBi-ZA/MODE-TASK#5]
Hej,

So I tried the tool. It produces the files as mentioned however I didn't find some post processing options.
We will get different clusters from a tSNE output. Is there any functionality to dump a PDB corresponding to the cluster centers in the programme.  I mean if we do the tSNE but can't say anything about the tSNE clusters or vectors then I guess the method is not much of a use as Gromacs already has the full fledged functionality for PCA and other basic dimensionality reduction techniques. Please let me know if there is anything in the pipeline to integrate post-processing of tSNE?

/SB

**Comment by michaelglenister** [comment]
@nizamibilal Perhaps you can comment on this

**Comment by nizamibilal** [comment]
@sbhakat @michaelglenister  

Thanks for using the MODE TASK. Unfortunately this feature is due for next version and will only be available in the future release of MODE TASK. But for now you can select a frame from your MD trajectory based on color coding from the t-SNE plot to represent a certain cluster. Nevertheless, t-SNE offers a insight into dimensionality of MD trajectory not inferred from PCA. 

Regards,
